spring:
  #    db
  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql

#    swagger
swagger:
  api:
    title: OnlineStore API
    description: This is the sample online store
    version: v1
    terms: termsOfService goes here
  contact:
    name: Company Inc.
    email: contact@gmail.com

